apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: MY-APP

resources:
- ../../base

images:
- name: ghcr.io/USER/MY-APP-api
  newTag: dev
- name: ghcr.io/USER/MY-APP-web
  newTag: dev

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: api
  spec:
    template:
      spec:
        containers:
        - name: api
          env:
          - name: NODE_ENV
            value: "development"
          - name: DATABASE_URL
            value: "postgres://app:app@postgres:5432/app"
          - name: REDIS_URL
            value: "redis://redis:6379"
